sonar.projectKey=devsecops-app
sonar.projectName=DevSecOps App
sonar.projectVersion=1.0

sonar.sources=app

sonar.host.url=http://13.126.95.115:9000
sonar.login=sqp_c04fb088618c291ccf2e623d1ef7243fce6321d6

